# Generated by Django 3.1.2 on 2020-10-16 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('resumen', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catego', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nombreMar', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['nombreMar'],
            },
        ),
        migrations.CreateModel(
            name='InstanciaAccesorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('devolver', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'En mantención'), ('o', 'En préstamo'), ('a', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Disponibilidad del producto', max_length=1)),
                ('accesorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.accesorio')),
            ],
            options={
                'ordering': ['devolver'],
            },
        ),
        migrations.AddField(
            model_name='accesorio',
            name='categoria',
            field=models.ManyToManyField(to='catalogo.Categoria'),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.marca'),
        ),
    ]
